#####################
# register a new user
POST http://localhost:4000/auth/register
Content-Type : application/json

{
    "name" : "Admin",
    "email" : "admin@gmail.com",
    "password" : "Qwerty12!",
    "role" : "admin"
}